name: Run Pylint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:devel

    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Install requirements
      run: make install -C ./AI

    - name: Run Pylint
      run: make lint -C ./AI
