name: Run Pylint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update package list and install SFML
      run: |
        sudo apt-get update -y
        sudo apt-get install libsfml-dev -y

    - name: Install requirements
      run: make install -C ./AI

    - name: Run Pylint
      run: make lint -C ./AI
